name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    - name: Install Theos
    run: |
     git clone --depth=1 https://github.com/theos/theos.git $THEOS
     bash $THEOS/bin/install-nic.sh
  env:
    THEOS: ${{ github.workspace }}/theos

    steps:
    - uses: actions/checkout@v4
    - name: Setup Theos SPM config
      run: make spm
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
